### PR TITLE
Added missing "Unlicense" value to licenses names

### PR DESCRIPTION
**Pull request by knshiro**
The issue softprops/bintray-sbt#39 should not be addressed by accepting non correct licenses but by adding the "Unlicense" value (cf https://bintray.com/docs/api/#_footnote_1) to `Licenses.Names`

### CODE REVIEW

**Comment by ulejon** [comment]
Isn't the meaning of the "Unlicense" license that the software is free and released to the public domain?
See this link: http://unlicense.org/

The need for not having a licence is still valid for private repositories.

**Comment by softprops** [comment]
It may just be a bad choice of name on bintray, the service's, behalf.

**Comment by ulejon** [comment]
Ok, I see.
So how do I use the "Unlicense" license in bintray-sbt?
licenses += ??

**Comment by softprops** [comment]
Yes. By default bintray-sbt will use the value of the sbt defined key [licenses](https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Keys.scala#L217)

**Comment by ulejon** [comment]
Thanx.
Currently I have the following defined in my plugins.sbt file: addSbtPlugin("me.lessis" % "bintray-sbt" % "0.1.2")

I guess your "Unlicense" changes isn't included in that version? Do you have an estimate on when the next release is due? Or do you have any nightly builds I can use?

**Comment by softprops** [comment]
A next release is a bit _overdue_ :). I've got some time this weekend where I think I can wrap that up and publish a new version.

**Comment by ulejon** [comment]
Sweet, I'll check for a fresh release on Monday morning :)

**Comment by ulejon** [comment]
Small addition, after reading more on the Bintray site I can confirm that Bintray links "Unlicense" to this page: http://unlicense.org/ 

So in other words, Unlicense is not the same thing as not having a license at all.
Wouldn't the best think be to enable skipping specifying a license in sbt?

**Pull request merged**
